format = " at $all"
add_newline = true 

[directory]
truncation_length = 1

[battery]
disabled = true

[aws]
disabled = true

[rust]
disabled = true

[java]
disabled = true

[package]
disabled = true

[lua]
disabled = true

[character]
success_symbol = '[➜](bold green)'

[nodejs]
disabled = true
