format = " at $all"
add_newline = false

[directory]
truncation_length = 1

[battery]
full_symbol = "🔋 "
charging_symbol = "⚡️ "
discharging_symbol = "💀 "

[[battery.display]]
threshold = 20
style = "bold red"

[[battery.display]]
threshold = 45
style = "bold yellow"

[aws]
disabled = true

[rust]
disabled = true

[java]
disabled = true

[package]
disabled = true
